### ISSUE TITLE
error for running the script?

### ISSUE THREAD

**Issue by ghost** [sjspielman/grabbag#2]
(base) lixinggbookpuro:grabbag-master lixingguang$ python align_pal2nal.py H5N1_HA_CDS.fas 
  File "align_pal2nal.py", line 140
    print "Back-translating protein alignment to a nucleotide alignment"
                                                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Back-translating protein alignment to a nucleotide alignment")?
(base) lixinggbookpuro:grabbag-master lixingguang$

**Comment by sjspielman** [comment]
This repository is extremely old and not maintained, for many years. I would not use any of this code.
